/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Venda;


import DAO.ClienteDAO;
import DAO.DepositoAreaDAO;
import DAO.ProdutoDAO;
import DAO.VendaDAO;
import Model.ClienteModel;
import Model.DepositoAreaModel;
import Model.ProdutoModel;
import Model.VendaModel;
import Model.VendaProdutoModel;
import java.awt.Color;
import Util.FormatField;
import Util.ValidateField;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author forster
 */
public class FrmVenda extends javax.swing.JFrame {

    private VendaModel vendaModel;
    
    public FrmVenda() {
        initComponents();
        
        this.vendaModel = new VendaModel();
        
        for(var cliente : new ClienteDAO().readComboBox()){
            comboBoxClientes.addItem(cliente);
        }
        
        listProdutos.setListData(new ProdutoDAO().readComboBox());
        
        if(vendaModel.getVendaProdutos().isEmpty()){
            jButton6.setEnabled(false);
        }
        
        populateTable();
        
        
    }
    
    private void populateTable(){
        
        String[][] data = new VendaDAO().read(null);
        
        String[] colunas = new String[]{"Id","Data Venda","Valor Total","Cliente"};
        
        DefaultTableModel tableModel = new DefaultTableModel(data, colunas);
        
        jTable1.setModel(tableModel);
    }
    
    private void populateComboBoxArea(int idProduto){
        
        
        for(var area : new DepositoAreaDAO().readComboBoxByProduto(idProduto)){
            comboBoxArea.addItem(area);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        comboBoxClientes = new javax.swing.JComboBox<>();
        fieldQuantidade = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        comboBoxArea = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listProdutos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));

        jLabel2.setText("Clientes");

        jLabel6.setText("Quantidade");

        jButton6.setText("Finalizar Venda");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        comboBoxClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboBoxClientesFocusLost(evt);
            }
        });

        fieldQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        fieldQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldQuantidadeFocusGained(evt);
            }
        });
        fieldQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldQuantidadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fieldQuantidadeMouseEntered(evt);
            }
        });

        jButton2.setText("Adicionar Produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comboBoxArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBoxAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboBoxAreaFocusLost(evt);
            }
        });
        comboBoxArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBoxAreaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboBoxAreaMouseExited(evt);
            }
        });

        listProdutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listProdutosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                listProdutosFocusLost(evt);
            }
        });
        listProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProdutosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listProdutos);

        jLabel1.setText("Area ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 237, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(fieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nova Venda", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Data Venda", "Valor Total", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Cancelar Venda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver Detalhes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxClientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxClientesFocusLost
        comboBoxClientes.setEnabled(false);
    }//GEN-LAST:event_comboBoxClientesFocusLost

    private void listProdutosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listProdutosFocusLost
        
        listProdutos.setSelectionBackground(Color.blue);
        listProdutos.setSelectionForeground(Color.white);
        
    }//GEN-LAST:event_listProdutosFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        double quantidadeEstoque = Double.parseDouble(comboBoxArea.getSelectedItem().toString().split(" - ")[2].replace(" Kg", ""));
        double quantidadePedido = Double.parseDouble(fieldQuantidade.getValue().toString());
        
        if(quantidadePedido > quantidadeEstoque){
            JOptionPane.showMessageDialog(null, "Quantidade inválida.", "ERRO", 2);
            
        }else{

            if(vendaModel.getCliente()== null){
                
                int idCliente = Integer.parseInt(
                        comboBoxClientes.getSelectedItem().toString().split(" - ")[0]
                );

                String nomeCliente = comboBoxClientes.getSelectedItem().toString().split(" - ")[1];

                ClienteModel fornecedorModel = new ClienteModel(idCliente, nomeCliente);

                vendaModel.setCliente(fornecedorModel);

            }

            int idProduto = Integer.parseInt(listProdutos.getSelectedValue().split(" - ")[0]);
            
            String descricaoProduto = listProdutos.getSelectedValue().split(" - ")[1];

            ProdutoModel produtoModel = new ProdutoModel(idProduto, descricaoProduto);
            
            DepositoAreaModel depositoAreaModel = new DepositoAreaModel(
                    Integer.parseInt(comboBoxArea.getSelectedItem().toString().split(" - ")[0]),
                    comboBoxArea.getSelectedItem().toString().split(" - ")[1]
            );

            VendaProdutoModel vendaProdutoModel = new VendaProdutoModel(
                    vendaModel, 
                    produtoModel, 
                    Double.parseDouble(fieldQuantidade.getValue().toString()), 
                    Double.parseDouble(
                        listProdutos.getSelectedValue().split(" - ")[2].replace("Valor Venda: R$ ", "")
                    ),
                    depositoAreaModel
            );
            
            double produtoDetalhesQuantidade = Double.parseDouble(comboBoxArea.getSelectedItem().toString().split(" - ")[2].replace(" Kg", ""));
            Date produtoDetalhesValidade = FormatField.returnDate(comboBoxArea.getSelectedItem().toString().split(" - ")[3].replace("Validade: ", ""));

            vendaProdutoModel.setProdutoDetalhesQuantidade(produtoDetalhesQuantidade);
            vendaProdutoModel.setProdutoDetalhesValidade(produtoDetalhesValidade);
            
            this.vendaModel.getVendaProdutos().add(vendaProdutoModel);

            JOptionPane.showMessageDialog(
                    null, 
                    "Item adicionado.\nValor Total: R$ "+vendaProdutoModel.getValorTotal(), 
                    "SUCESSO", 
                    1);

            if(!jButton6.isEnabled()){
                jButton6.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        VendaDAO vendaDAO = new VendaDAO();
        
        boolean resultado = vendaDAO.create(vendaModel);
        
        if(resultado){
            JOptionPane.showMessageDialog(null, "Sucesso ao realizar venda.", "SUCESSO", 2);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao realizar venda.", "ERRO", 2);
            this.dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        
        VendaDAO dao = new VendaDAO();
        
        boolean sucesso = dao.delete(id);
        
        if(sucesso){
            JOptionPane.showMessageDialog(null, "Sucesso ao cancelar venda", "SUCESSO", 2);
            
            populateTable();
            
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao cancelar venda", "ERRO", 2);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        
        var janela = new FrmDetalhesVenda(id);
        
        janela.setVisible(true);
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        //
    }//GEN-LAST:event_jTable1FocusLost

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        //
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //
    }//GEN-LAST:event_jTable1MouseClicked

    private void comboBoxAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxAreaFocusGained
        //
    }//GEN-LAST:event_comboBoxAreaFocusGained

    private void fieldQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldQuantidadeFocusGained
        
    }//GEN-LAST:event_fieldQuantidadeFocusGained

    private void comboBoxAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxAreaFocusLost
            
        
            
        
    }//GEN-LAST:event_comboBoxAreaFocusLost

    private void listProdutosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listProdutosFocusGained
        //
    }//GEN-LAST:event_listProdutosFocusGained

    private void listProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProdutosMouseClicked
        comboBoxArea.removeAllItems();
        
        int idProduto = Integer.parseInt(listProdutos.getSelectedValue().split(" - ")[0]);
        
        populateComboBoxArea(idProduto);
        
       
    }//GEN-LAST:event_listProdutosMouseClicked

    private void comboBoxAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxAreaMouseClicked
        
    }//GEN-LAST:event_comboBoxAreaMouseClicked

    private void fieldQuantidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldQuantidadeMouseEntered
        //
    }//GEN-LAST:event_fieldQuantidadeMouseEntered

    private void fieldQuantidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldQuantidadeMouseClicked
        
        
        
    }//GEN-LAST:event_fieldQuantidadeMouseClicked

    private void comboBoxAreaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxAreaMouseExited

    }//GEN-LAST:event_comboBoxAreaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxArea;
    private javax.swing.JComboBox<String> comboBoxClientes;
    private javax.swing.JSpinner fieldQuantidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listProdutos;
    // End of variables declaration//GEN-END:variables
}
